language: rust
rust:
  - 1.36.0
  - nightly
  - stable
script:
  - if [[ "$(rustc --version)" =~ -(dev|nightly) ]]; then cargo bench; fi
  - if [[ "$(rustc --version)" =~ 1.36.0 ]]; then cp test-oldest-Cargo.lock Cargo.lock; fi
  - cargo test
  - cargo test --release
  - cargo test --no-default-features --features hashbrown
  - cargo test --release --no-default-features --features hashbrown
