language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - if [[ "$(rustc --version)" =~ -(dev|nightly) ]]; then cargo test --features bench; else ! cargo test --features bench; fi
  - cargo test
